name: pages build and deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18 and cache yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies (yarn)
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          CI: false

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
